# Generated by Django 5.0.7 on 2024-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('tags', models.ManyToManyField(to='charity.tag')),
            ],
        ),
    ]
