# Generated by Django 5.0.7 on 2024-08-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_article_author_alter_article_date_alter_article_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
