# Generated by Django 5.0.7 on 2024-08-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='charity.category'),
        ),
    ]
