# Generated by Django 5.0.7 on 2024-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_category_alter_article_img_article_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles_amount', to='charity.category'),
        ),
    ]
