# Generated by Django 5.0.7 on 2024-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_alter_category_options_alter_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='')),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
